sudo: required
language: python
dist: bionic
services:
- docker
env:
  global:
    - secure: gjxlBnHvMHq2wzqk2SslGRJ3xm25Fb3P7wzexuu0ye4enc7ozziNyZRSipviQsm63zZzMzouaUMhY2q5ffhZmzq2/HgOQU+ax3sFwaLizx0ANBNNxyq/CKkSMbeZvdYU+Pt6qZLPViwHcSv+6ajgpAPOjj5luuqimIalGqYnIx+j2okvTyj79FB/+Dv/VSizCUuHnuWR6dC2QXRehK52CcE0sKHdsFR+Xm/29uFhpVJ0I8fgmusqJgXnltc2qt/GSwRdFUC6SK/a0xnRpE60o/HjFwD/fo0/Y7FBbUv/f3VF318P3TuMVZghoam+a0w0w9wiSbUoMEyEhVveWVrPxVqBbuYGAnqcBZUKB8lmBw7lKXxELlzPfxKs/dWO9q8Cc8fFsxciH83gIrKqkqg/P0UG5ZR1YpyhhkpnmB73Ib7u1WMgrRNeIsemx95S7+nG2RDBsVHyhV/3uu6R3CLAcMuqNIuarGi4JiUzG1y2CGKWor43CarLvtP79GVm6pJJKz7Tfk9JHYRi1H4kT3ZXU22uszh1ob5tRnGhDrdJkloriD237Qfr6A2y6lAJBL4mkEk/76jOqT8rio5NS9JLiX03frk+eSQuN0WvLcqqsfvPr029eRoxEEOtOb1xicIJh9XnUTbhHzWR+jdd92rl3cSznbxmpMqcYyoo7e7jjTk=
before_install:
  - echo $TEST_FILE
# - echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u itzsrikanth --password-stdin
branches:
  only:
  - master
  - production
  - development
script: cd server && docker build -t server:dev .
# after_success:
# - docker push server:dev
