sudo: required
language: python
dist: bionic
services:
- docker
env:
  global:
  - secure: roHf74Zx8Ac55x1tIt3Ucz9Gmz9wJhq1iyGTX+UhVzDnM10Gf65pbwBrit9qpUSRXKYE2i2fp845eFcjHkTkATw3Hu1RTk4XQriaC/TV/co1A9Lo3T1tke2eHJ9oVqj9FH6S2VD171N/HJoCiY04HmBq2FdrVJXCxDvXzi+lY/MBF3ot8ZvAM1+LldM8h/s+3mUXDOIVfxc3o8q34Q/x0ZA5GtYzQQey6rlf4gWn8PfgIaEzOHmpiJQFKuAKlw6WzQqyU/x2jVT63yn1d12qGO2vLwdkvHocNIhxN5UPtUhCGibxMKR/SZucYM3qb/C2y3V9dMyn3bnoUfapixEVE5dGYRs+5V5SK7T5Bp/W1OWH4XBPnB0bd44lT79KVjt+C0G/npuGbpHLjSIJOH6bBcvKueODx0TDLqZnzTAFgoauyX6MIIh22N5j2P2WfRp0jR5FmKdyXa5N8G7AQiSrZ1R96h/hv+/MmVOtEEpbNFjux3BmJ8O3EyU8SWGQT6BmWT2HF8dbY4NfcJ0ZwLuITBow/Bf/I1HnLPlIJpyVfHGiTnQTwbCA7XFTH/bfFpRLwxkueAlKs45VsjEWvD+LtRhma6b6pUkhdHH15yflzZ2Al8tmSx5XvJanGbvwSPw2tL2bglACcZwVGJB+p3faXIBh6TFXmRKdP5g23YtZVfk=
  - CAMPFIRE_TOKEN=abc123
before_install:
- echo $ALPHA > test.txt && cat test.txt
branches:
  only:
  - master
  - production
  - development
script: cd server && docker build -t server:dev .
